Toloka/docs

.yfm
Added feedback and crawler options to the configuration file
=> Fixes to config file

en/template-builder/templates/audio-transcript.md, en/template-builder/templates/copywriting.md, en/template-builder/templates/data-search.md, en/template-builder/templates/image-classification.md, en/template-builder/templates/index.md, en/template-builder/templates/sbs-audio.md, en/template-builder/templates/sbs-image.md, en/template-builder/templates/sbs-video.md, en/template-builder/templates/survey.md, en/template-builder/templates/video-moderation.md, en/template-builder/toc.yaml, ru/template-builder/templates/index.md, ru/template-builder/templates/sbs-audio.md, ru/template-builder/templates/sbs-image.md, ru/template-builder/templates/sbs-video.md, ru/template-builder/toc.yaml
Updated Audio side-by-side preset, added new Image side-by-side and Video side-by-side presets
=> DOC-10192: Added new preset descriptions for Template Builder

en/api/concepts/create-bonus.md, en/api/concepts/create-prj.md, en/api/concepts/tb-config.md, en/api/toc.yaml
=> DOCSUP-30361.translation

en/api/concepts/tasks.md
=> DOCSUP-32967: received translation toloka api

en/_includes/template-builder-toc.yaml, en/template-builder/templates/content-moderation.md, en/template-builder/templates/index.md, en/template-builder/templates/text-classification.md
We have added a description of the new template «Sentiment analysis & content moderation»
=> DOCSUP-32456: add a description of the new template

en/guide/_includes/toloka-requester-source/id-toloka-requester-source/set-price.md, en/guide/tutorials/questionnaire-other.md
Pool preset in Survey on third-party platform
=> DOCSUP-36736: Pool preset in Survey on third-party platform

en/guide/tutorials/questionnaire-other.md
Add-on in the "Survey on third-party platform" tutorial
=> DOCSUP-37195: Add-on in the "Survey on third-party platform" tutorial

en/glossary.md, en/guide/_includes/toloka-requester-source/id-toloka-requester-source/instruction-note.md, en/guide/_includes/toloka-requester-source/id-toloka-requester-source/instructions.md, en/guide/_includes/toloka-requester-source/id-toloka-requester-source/media-files.md, en/guide/concepts/captcha.md, en/guide/concepts/first-project.md, en/guide/concepts/pool-main.md, en/guide/concepts/pool_poolparams.md, en/guide/concepts/task_upload.md, en/guide/tutorials/audio-classification.md, en/guide/tutorials/audit-of-planogram-of-product-placement-in-store.md, en/guide/tutorials/content-moderation.md, en/guide/tutorials/image-classification.md, en/guide/tutorials/internet-search.md, en/guide/tutorials/monitoring-objects-in-organizations.md, en/guide/tutorials/monitoring.md, en/guide/tutorials/price-tag.md, en/guide/tutorials/questionnaire-other.md, en/guide/tutorials/questionnaire-toloka.md, en/guide/tutorials/record-audio.md, en/guide/tutorials/selection.md, en/guide/tutorials/side-by-side.md, en/guide/tutorials/transcript-audio.md, en/guide/tutorials/video-moderation.md, en/guide/tutorials/walk.md
Adding the info about the new "Select media files" feature
=> DOCSUP-37706: Task upload update

en/_includes/template-builder-toc.yaml, en/template-builder/templates/index.md, en/template-builder/templates/spatial-crowdsourcing.md, en/template-builder/templates/video-moderation.md
Added a description of the new template.
=> DOCSUP-31581: add a description of the new template

en/guide/_includes/toloka-requester-source/id-toloka-requester-source/media-files.md, en/guide/concepts/cloud-storage.md, en/guide/concepts/spec.md
Add information about media files to the "Where to store files" page.
=> DOCSUP-38852: Add information about media files to the "Where to store files" page

en/glossary.md, en/toloka-apps/_includes/queue.md, en/toloka-apps/_includes/template.md, en/toloka-apps/_includes/upload-data.md, en/toloka-apps/concepts/add-task.md
Adding the batch labeling queue.
=> DOCSUP-39174: Batch labeling queue

en/glossary.md, en/guide/concepts/dynamic-pricing.md, en/guide/concepts/efficiency-metrics/index.md
Headers in the glossary and the notes
=> DOCSUP-40821: Headers in the glossary and the notes

en/guide/concepts/unwanted.md
Update the "What tasks can't be placed in Toloka?" page.
=> DOCSUP-41206: Update the "What tasks can't be placed in Toloka?" page

en/guide/_includes/toloka-requester-source/id-toloka-requester-source/array.md, en/guide/_includes/toloka-requester-source/id-toloka-requester-source/boolean.md, en/guide/_includes/toloka-requester-source/id-toloka-requester-source/coordinates.md, en/guide/_includes/toloka-requester-source/id-toloka-requester-source/file.md, en/guide/_includes/toloka-requester-source/id-toloka-requester-source/float.md, en/guide/_includes/toloka-requester-source/id-toloka-requester-source/integer-float.md, en/guide/_includes/toloka-requester-source/id-toloka-requester-source/integer.md, en/guide/_includes/toloka-requester-source/id-toloka-requester-source/json-string.md, en/guide/_includes/toloka-requester-source/id-toloka-requester-source/json.md, en/guide/_includes/toloka-requester-source/id-toloka-requester-source/string.md, en/guide/_includes/toloka-requester-source/id-toloka-requester-source/tsv-json.md, en/guide/_includes/toloka-requester-source/id-toloka-requester-source/tsv-string.md, en/guide/_includes/toloka-requester-source/id-toloka-requester-source/url.md, en/guide/concepts/efficiency-metrics/submitting-tasks.md, en/guide/concepts/image-segmentation-project1.md, en/guide/concepts/image-segmentation-project3.md, en/guide/concepts/incoming.md, en/guide/concepts/pool_csv.md
Description for the data types and the usage examples
=> DOCSUP-41201: Description for the data types and the usage examples

en/_includes/template-builder-toc.yaml, en/template-builder/templates/index.md, en/template-builder/templates/product-photo-search.md
Product photo search preset description
=> DOCSUP-39666

en/template-builder/operations/work-with-data.md, en/template-builder/reference/field.quiz.md
=> DOCSUP-42682: Добавить пример для field.quiz

en/_includes/template-builder-toc.yaml, en/template-builder/templates/index.md, en/template-builder/templates/named-entity-recognition.md
Named entity recognition preset description
=> DOCSUP-39672

en/template-builder/reference/view.action-button.md, en/template-builder/reference/view.alert.md
Added an example and a list of components to view.action-button. Added a list a components to view.alert.
=> DOCSUP-43690

en/template-builder/reference/view.collapse.md
Added a list of components and an example
=> DOCSUP-43758

en/template-builder/reference/view.audio.md
тикет: https://st.yandex-team.ru/DOCSUP-43692
DOCSUP-43692
=> DOCSUP-43692:  Добавить пример для view.audio

en/template-builder/reference/field.date.md, en/template-builder/reference/field.number.md, en/template-builder/reference/field.radio-group.md, en/template-builder/reference/field.select.md
Adding examples for field.date, field.number, field.radio-group and field.select
=> DOCSUP-52327: Adding examples for the components

en/template-builder/reference/plugin.hotkeys.md, en/template-builder/reference/plugin.toloka.md, en/template-builder/reference/plugin.trigger.md
Adding examples for plugin.hotkeys, plugin.toloka and plugin.trigger
=> DOCSUP-52330: Adding examples for templates
